spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sonpexel@gmail.com
    password: oiekkyvlpnjyyaid
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: "jdbc:mysql://localhost:3306/ltdd"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true