spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sonpexel@gmail.com
    password: oiekkyvlpnjyyaid
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true